version: '3'
services:
  marblecutter:
    build: .
    environment:
      - PYTHONPATH=.
      - CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    volumes:
      - .:/opt/marblecutter/
    ports:
      - "8000:8000"
    entrypoint: python3
    command: server.py
